# Generated by Django 5.2 on 2025-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='post/placeholder.webp', null=True, upload_to='post/'),
        ),
    ]
